#!/usr/bin/env sh

#
# wm independent hotkeys
#

# terminal emulator
super + Return
	kitty --single-instance

# program launcher
super + d
    rofi -show drun -config ~/.config/rofi/configs/config.rasi -width 420

super + p
    ~/.config/rofi/scripts/powermenu

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + shift + q
	bspc node -c

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}' --follow

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# (rotate clockwise/counterclockwise)/balance
super + {_,shift,alt} + e
  bspc node $(bspc query -N -n -n .!leaf || echo @/) {-R 90,-R 270,-B}

# focus the node in the given direction
ctrl + {h,j,k,l}
    ~/dev/bspwm-nvim-tmux-navigation/windowSwitcher.sh {west,south,north,east}

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}


# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

super + shift + s
    maim -o --select | xclip -selection clipboard -t image/png

super + {b, B}
    brightnessctl set 10%{+,-}

super + {v, V}
    amixer -D pulse sset Master 5%{+,-}

# Scrachpads
super + ctrl + Return
    ~/.local/bin/scripts/scpad

super + ctrl + c
    ~/.local/bin/scripts/chatgpt

super + r : {h,j,k,l}
    STEP=20; SELECTION={1,2,3,4}; \
    bspc node -z $(echo "left -$STEP 0,bottom 0 $STEP,top 0 -$STEP,right $STEP 0" | cut -d',' -f$SELECTION) || \
    bspc node -z $(echo "right -$STEP 0,top 0 $STEP,bottom 0 -$STEP,left $STEP 0" | cut -d',' -f$SELECTION)

