#! /bin/sh

export SXHKD_SHELL='/usr/bin/sh'

if grep -q "closed" /proc/acpi/button/lid/LID/state; then
    xrandr --output eDP-1 --off
    bspc monitor DP-1-2 -d chat term web music code notes 
    bspc desktop Desktop --remove
    bspc monitor --reset-desktops chat term web music code notes
else 
    bspc monitor -d chat term web music code notes 
fi

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh 2>~/polylog &
picom --experimental-backends -b #000000 &
dunst &
feh --bg-scale ~/wallpapers/ocean.jpg
/usr/libexec/polkit-gnome-authentication-agent-1 &
setxkbmap us
~/.config/bspwm/delayXmodmap.sh &

bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Get correct padding from polybar
bspc config top_padding 40px
bspc config ignore_ewmh_struts true

bspc config focused_border_color "#ebbcba"
bspc config normal_border_color "#6e6a86"
bspc config border_width         2
