import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 1

[colors]
draw_bold_text_with_bright_colors = true

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[font]
size = 14

[font.bold]
family = "my-chosen-font-family"
style = "Bold"

[font.italic]
family = "my-chosen-font-family"
style = "Italic"

[font.normal]
family = "my-chosen-font-family"
style = "Medium"

[window.padding]
x = 5
y = 5

[mouse]
hide_when_typing = true
